a = 1
a = "priya"
print(a)
name = "supriya"
dio = "i didn\\'t like to learn java"
print(dio) 
dio2 = "i  didn\'t like to learn java"
print(dio2)
name = "\npython.\nfull stack developer"
print(name)
lang = "\tjava"
print(lang)
aa = "concatenation"
print(aa)
num1 = "sup"
num2 = "priya"
print(num1+num2)
num3 = 22
num4 = 7
print(num3+num4)
top = "slicing"
print(top)
str = "i am regularly watch python class"
print(str[5])
print(str[3:7])
print(str[::3])
print(str[-4])
print(str[-13:-1])
print(str[:-19:-1])