top1 = "tuple"
print(top1)
a = (1,2,3,4,5,6,7,8,9,0)
print(a)
b = 321
c = str(b)
d = c[::-1]
e = int(d)
print(b + e)
top2 = "set"
print(top2)
aa = {1,2,3,4,5,6}
print(aa)
top3 = "add"
print(top3)
bb = {1,2,3,4,5,6}
print(bb.add(8))
cc =  {1,2,3,4,5,6}
print(cc.remove(4))
top4 = "dict"
print(top4)
dd = {1:"priya",2:"ammu",3:"thambi"}
dd[4] = "suriya"
print(dd)
ee =  {1:"priya",2:"ammu",3:"thambi"}
ee[3] = "ayyapa"
print(ee)
ff = {1:"priya",2:"ammu",3:"thambi"}
ff.pop(1)
print(ff)

