top = "arithmetic"
print(top)
a = 8
b = 4
c = 5
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)
top2 = "assignment"
print(top2)
aa = 8
bb = 4
cc = 5
aa += 5
print(aa)
bb -= 4
print(bb)
aa *= 3
print(aa)
cc /= 1
print(cc)
aa %= 2
print(aa)
aa **= 2
print(aa)
top3 = "comparison"
print(top3)
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
top4 = "logical"
print(top4)
print(a != b and a > b)
print(a > b or a < b)
print( not (a != b))
top5 = "bitwise"
print(top5)
print(a & b)
print(a | b)
print(a ^ b)
print( ~a )
print(a << b)
print(a >> b)