a=(2,3,4,5,6,7,8)
b=list(a)
b[0]=1
c=tuple(b)
print(c)
name=[1,2,3,4,5,6,7,8,9]
new=tuple(name)
print(new)
a={1,2,3,4,5}
a.add(6)
a.remove(3)
print(a,c)
a={'one':'aravind','two':'balaguru','three':'abishek'}
a['one']='arun'
a['four']='anand'
a.pop('two')
b=a.values()
c=a.keys()
print(a)
print(b)
print(c)
print(a['four'])